### PR TITLE
Pasting from clipboard

### PR DESCRIPTION
**Pull request by Nithe14**
There is a simple function that allows you to paste your pattern from the clipboard. Please note that I haven't thoroughly tested it 😉

### CODE REVIEW

**Comment by lfrati** [comment]
The idea is interesting but there are a few problems:
1. dealing with the clipboard is messy (e.g. xclip)
2. onesearch is currently based on the assumption that you input one character at a time

Concerning 1. I was thinking that we can easily make the search function take some text, and you can make a custom binding to pass what you prefer.
e.g.
```lua
  vim.keymap.set({ "o", "n" }, "y/", ":lua require('onesearch').search(io.popen(\"xclip -o\", \"r\"))<CR>")
```
Point 2. is trickier. If you are allowed to pass in arbitrary chunks of text the search logic should be changed to deal with it. A possible workaround would be to only allow to pass in text coming from the current buffer, so that you are guaranteed to hit at least one match (e.g. word under cursor or visual selection). Would that be ok for your use case?

**Comment by Nithe14** [comment]
You're absolutely right. Passing arguments to the search function is a much better option than using the dedicated xclip function, which doesn't work for everyone. I've implemented your idea in this commit [3f11da1](https://github.com/lfrati/onesearch.nvim/pull/6/commits/3f11da1d3a10ae7aaf64fda53aadb75b00370439). The code might be a bit messy cause I did it quickly. Please take a look.

On another note, I don't think allowing users to paste only from the current buffer is a good idea. In my case, I often search for text copied from browser in the code or configurations. So limiting pasting to just the buffer isn't what I'm looking for. That aside, dealing with blocks of text is actually a problem. I didn't realize before that the pasted pattern doesn't work with partial matching logic (such as errors). In such cases, we could trim and check the pasted pattern until it's empty, but this might slow down the plugin significantly. What do you think?

Just to be clear, I had to modify `io.popen("xclip -o", "r")` to `:read("*a")` because it wasn't working for me. So my final keybind looks like this:
```lua
vim.keymap.set({ "o", "n" }, "<leader>/", ":lua require('onesearch').search(io.popen(\"xclip -o\", \"r\"):read(\"*a\"))<CR>")
```

**Comment by lfrati** [comment]
I've added part of your contribution into 044ed24 (there was an extra file committed, and I changed how to handle passing a seed text). 
I've made it so when you pass a "seed" text to `M.search(seed)`:
- if the seed is found, search continues normally
- if the seed is NOT found, the whole pattern is marked as error (instead of searching for the largest subset of it that might be present somewhere) and can be deleted with a single K_BS to start a new search.
```lua
    -- when a seed is used for pattern we look for it in the text
    -- if not found we mark the whole pattern as an error.
    -- (if the seed does not exist in the text, shame on you ;p)
    if seed and #seed > 0 then
        matches, next, color_head = visible_matches(seed)
        show(matches, color_head)
        if #matches > 0 then
            pattern = seed
            last_match = seed
        else
            errors = seed
        end
    end
```
I've also added a wrapper around M.search() -> M.visual_search() that calls the search function with the value of the current visual selection:
```lua
    vim.keymap.set({ "v" }, "/", ":<C-u>lua require('onesearch').visual_search()<CR>")
```
Thank you for your help, I'll mention it  in the README :)

**Comment by Nithe14** [comment]
This is great! Now I can even remap '#' key to use onesearch instead of the default nvim search engine. Thank you! 😁

**Pull request closed without merging**
